#!/bin/bash

echo "🚀 Brandr API Deployment to Render"
echo "=================================="
echo ""
echo "Since you already have a Render account, follow these steps:"
echo ""
echo "1. Go to: https://dashboard.render.com"
echo "2. Click 'New +' → 'Web Service'"
echo "3. Connect your GitHub repository: usebrandr/usebrandr"
echo "4. Configure the service:"
echo "   - Name: brandr-api"
echo "   - Environment: Node"
echo "   - Build Command: npm install"
echo "   - Start Command: node server.js"
echo "   - Health Check Path: /api/health"
echo ""
echo "5. Add Environment Variables:"
echo "   - MONGODB_URI: mongodb+srv://reecebforbes:Banter8612!@waitlist.zwsho5.mongodb.net/?retryWrites=true&w=majority&appName=Waitlist"
echo "   - NODE_ENV: production"
echo ""
echo "6. Click 'Create Web Service'"
echo ""
echo "After deployment, you'll get a URL like: https://brandr-api.onrender.com"
echo ""
echo "Once you have the URL, run: ./update-frontend.sh <YOUR_RENDER_URL>"
echo "" 