services:
  - type: web
    name: usebrandr
    env: node
    plan: starter
    rootDir: .
    buildCommand: |
      echo "Current directory: $(pwd)"
      echo "Listing files:"
      ls -la
      echo "Building from root directory..."
      npm install
      echo "Build completed successfully"
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: waitlist
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
